### ISSUE TITLE
SIGSEGV when running cf-terraforming generate --resource-type "cloudflare_tunnel"

### ISSUE THREAD

**Issue by Weshnaw** [cloudflare/cf-terraforming#568]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

v0.12.0

### Expected outcome

I expect an output of terraform code

### Actual outcome

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x93a4c8]

goroutine 1 [running]:
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.generateResources.func1(0xeb1260?, {0xa4b7f3?, 0x4?, 0x4?})
	/home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/generate.go:1102 +0x5248
github.com/spf13/cobra.(*Command).execute(0xeb1260, {0xc000155680, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xeb0f80)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.Execute()
	/home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/root.go:30 +0x25
main.main()
	/home/runner/work/cf-terraforming/cf-terraforming/cmd/cf-terraforming/main.go:8 +0x17
```

### Steps to reproduce

1. have an existing cloudflare tunnel
2. add CLOUDFLARE_API_TOKEN env variable with edit permissions to cloudflare tunnels
3. create minimal `cloudflare.tf`
4. run terraform init
5. run cf-terraforming generate --resource-type "cloudflare_tunnel" -a account_id
<details>

<summary>cloudflare.tf</summary>

```
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}

provider "cloudflare" {
}
```
</details>

**Comment by jacobbednarz** [comment]
you'll need to use the terraform provider 4.x as the resource doesn't exist in 3.x (it was renamed with the upgrade).
