### ISSUE TITLE
Access rules panic on insufficient credentials

### ISSUE THREAD

**Issue by bobrik** [cloudflare/cf-terraforming#57]
```
DEBU[0000] Importing Access Rule data
DEBU[0000] Processing zone                               ID=abc Name=foo.org
DEBU[0000] error from makeRequest: HTTP status 401: invalid credentials
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x14459a8]

goroutine 1 [running]:
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.glob..func3(0x196dda0, 0xc0000e6630, 0x0, 0xb)
	/Users/bobrik/cf-repos/cf-terraforming/internal/app/cf-terraforming/cmd/access_rule.go:64 +0x228
github.com/spf13/cobra.(*Command).execute(0x196dda0, 0xc0000e6420, 0xb, 0xb, 0x196dda0, 0xc0000e6420)
	/Users/bobrik/cf-repos/cf-terraforming/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x196d420, 0xc00013df88, 0x10076bf, 0xc000088058)
	/Users/bobrik/cf-repos/cf-terraforming/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/bobrik/cf-repos/cf-terraforming/vendor/github.com/spf13/cobra/command.go:800
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.Execute()
	/Users/bobrik/cf-repos/cf-terraforming/internal/app/cf-terraforming/cmd/root.go:38 +0x32
main.main()
	/Users/bobrik/cf-repos/cf-terraforming/cmd/cf-terraforming/main.go:6 +0x20
```

Compare to `account_member`, which silently swallows the error:

```
DEBU[0000] Importing Account Member data
DEBU[0000] error from makeRequest: HTTP status 403: insufficient permissions
```

I'm not sure which one is the preferred way, but it should be the same between them.

This is the line where it panics on dereference (`accessRules  == nil`):

* https://github.com/cloudflare/cf-terraforming/blob/0f353216bb8/internal/app/cf-terraforming/cmd/access_rule.go#L60

**Comment by bobrik** [comment]
It's probably a good idea to log errors on a higher log level than debug:

* https://github.com/cloudflare/cf-terraforming/blob/0f353216bb8/internal/app/cf-terraforming/cmd/access_rule.go#L56-L58
